/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* top =  1  *)
(* src = "maquina.v:1" *)
module maquina_synth(clk, reset, umbralMF, umbralVC, umbralD, FifoFull, FifoEmpty, FifoWrite, FifoRead, init_out, idle_out, active_out, error_out);
  (* src = "maquina.v:34" *)
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _30_;
  wire _31_;
  wire _32_;
  wire _33_;
  wire _34_;
  wire _35_;
  wire _36_;
  wire _37_;
  wire _38_;
  wire _39_;
  (* src = "maquina.v:7" *)
  input FifoEmpty;
  (* src = "maquina.v:6" *)
  input FifoFull;
  (* src = "maquina.v:9" *)
  input FifoRead;
  (* src = "maquina.v:8" *)
  input FifoWrite;
  (* src = "maquina.v:12" *)
  output active_out;
  (* src = "maquina.v:1" *)
  input clk;
  (* src = "maquina.v:13" *)
  output error_out;
  (* src = "maquina.v:11" *)
  output idle_out;
  (* src = "maquina.v:10" *)
  output init_out;
  (* src = "maquina.v:2" *)
  input reset;
  (* onehot = 32'd1 *)
  wire [4:0] state;
  (* src = "maquina.v:5" *)
  input umbralD;
  (* src = "maquina.v:3" *)
  input umbralMF;
  (* src = "maquina.v:4" *)
  input umbralVC;
  NOT _40_ (
    .A(umbralD),
    .Y(_06_)
  );
  NOT _41_ (
    .A(FifoFull),
    .Y(_07_)
  );
  NOT _42_ (
    .A(reset),
    .Y(_08_)
  );
  NOT _43_ (
    .A(state[3]),
    .Y(_09_)
  );
  NOR _44_ (
    .A(FifoRead),
    .B(FifoWrite),
    .Y(_10_)
  );
  NOT _45_ (
    .A(_10_),
    .Y(_11_)
  );
  NOR _46_ (
    .A(_07_),
    .B(_10_),
    .Y(_12_)
  );
  NAND _47_ (
    .A(FifoFull),
    .B(_11_),
    .Y(_13_)
  );
  NAND _48_ (
    .A(state[1]),
    .B(_13_),
    .Y(_14_)
  );
  NOR _49_ (
    .A(umbralMF),
    .B(umbralVC),
    .Y(_15_)
  );
  NAND _50_ (
    .A(_06_),
    .B(_15_),
    .Y(_00_)
  );
  NOR _51_ (
    .A(_09_),
    .B(_00_),
    .Y(_16_)
  );
  NOR _52_ (
    .A(_08_),
    .B(_16_),
    .Y(_17_)
  );
  NAND _53_ (
    .A(_14_),
    .B(_17_),
    .Y(_02_)
  );
  NAND _54_ (
    .A(FifoEmpty),
    .B(FifoFull),
    .Y(_18_)
  );
  NOT _55_ (
    .A(_18_),
    .Y(_19_)
  );
  NOR _56_ (
    .A(state[4]),
    .B(state[2]),
    .Y(_20_)
  );
  NOT _57_ (
    .A(_20_),
    .Y(_21_)
  );
  NOR _58_ (
    .A(_08_),
    .B(_20_),
    .Y(_22_)
  );
  NAND _59_ (
    .A(reset),
    .B(_21_),
    .Y(_23_)
  );
  NAND _60_ (
    .A(_19_),
    .B(_22_),
    .Y(_24_)
  );
  NAND _61_ (
    .A(reset),
    .B(state[1]),
    .Y(_25_)
  );
  NOT _62_ (
    .A(_25_),
    .Y(_26_)
  );
  NAND _63_ (
    .A(_12_),
    .B(_26_),
    .Y(_27_)
  );
  NAND _64_ (
    .A(_24_),
    .B(_27_),
    .Y(_03_)
  );
  NOR _65_ (
    .A(FifoEmpty),
    .B(FifoFull),
    .Y(_28_)
  );
  NOT _66_ (
    .A(_28_),
    .Y(_29_)
  );
  NAND _67_ (
    .A(reset),
    .B(_18_),
    .Y(_30_)
  );
  NOR _68_ (
    .A(_28_),
    .B(_30_),
    .Y(_31_)
  );
  NAND _69_ (
    .A(state[4]),
    .B(_31_),
    .Y(_32_)
  );
  NAND _70_ (
    .A(reset),
    .B(state[0]),
    .Y(_33_)
  );
  NAND _71_ (
    .A(_32_),
    .B(_33_),
    .Y(_05_)
  );
  NAND _72_ (
    .A(state[2]),
    .B(_31_),
    .Y(_34_)
  );
  NAND _73_ (
    .A(reset),
    .B(state[3]),
    .Y(_35_)
  );
  NOT _74_ (
    .A(_35_),
    .Y(_36_)
  );
  NAND _75_ (
    .A(_00_),
    .B(_36_),
    .Y(_37_)
  );
  NAND _76_ (
    .A(_34_),
    .B(_37_),
    .Y(_04_)
  );
  NAND _77_ (
    .A(state[4]),
    .B(_28_),
    .Y(_38_)
  );
  NOT _78_ (
    .A(_38_),
    .Y(active_out)
  );
  NAND _79_ (
    .A(state[2]),
    .B(FifoEmpty),
    .Y(_39_)
  );
  NOR _80_ (
    .A(FifoFull),
    .B(_39_),
    .Y(idle_out)
  );
  NOR _81_ (
    .A(_23_),
    .B(_29_),
    .Y(_01_)
  );
  DFF _82_ (
    .C(clk),
    .D(_02_),
    .Q(state[0])
  );
  DFF _83_ (
    .C(clk),
    .D(_03_),
    .Q(state[1])
  );
  DFF _84_ (
    .C(clk),
    .D(_04_),
    .Q(state[2])
  );
  DFF _85_ (
    .C(clk),
    .D(_05_),
    .Q(state[3])
  );
  DFF _86_ (
    .C(clk),
    .D(_01_),
    .Q(state[4])
  );
  (* src = "maquina.v:34" *)
  \$_DLATCH_P_  _87_ (
    .D(_00_),
    .E(state[3]),
    .Q(init_out)
  );
  assign error_out = 1'h0;
endmodule
