/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* dynports =  1  *)
(* top =  1  *)
(* src = "maquina.v:1" *)
module maquina_synth(clk, reset, umbralMF, umbralVC, umbralD, Fifo_empties, Fifo_errors, init_out, idle_out, active_out, error_out, umbralMF_out, umbralVC_out, umbralD_out, state_estr, next_state_estr);
  (* src = "maquina.v:25" *)
  wire [3:0] _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _30_;
  wire _31_;
  wire _32_;
  wire _33_;
  wire _34_;
  wire _35_;
  wire _36_;
  wire _37_;
  wire _38_;
  wire _39_;
  wire _40_;
  wire _41_;
  (* src = "maquina.v:7" *)
  input [4:0] Fifo_empties;
  (* src = "maquina.v:8" *)
  input [4:0] Fifo_errors;
  (* src = "maquina.v:11" *)
  output active_out;
  (* src = "maquina.v:2" *)
  input clk;
  (* src = "maquina.v:12" *)
  output error_out;
  (* src = "maquina.v:10" *)
  output idle_out;
  (* src = "maquina.v:9" *)
  output init_out;
  (* src = "maquina.v:17" *)
  output [3:0] next_state_estr;
  (* src = "maquina.v:3" *)
  input reset;
  (* src = "maquina.v:16" *)
  output [3:0] state_estr;
  (* src = "maquina.v:6" *)
  input umbralD;
  (* src = "maquina.v:15" *)
  output umbralD_out;
  (* src = "maquina.v:4" *)
  input umbralMF;
  (* src = "maquina.v:13" *)
  output umbralMF_out;
  (* src = "maquina.v:5" *)
  input umbralVC;
  (* src = "maquina.v:14" *)
  output umbralVC_out;
  NOT _42_ (
    .A(Fifo_errors[2]),
    .Y(_01_)
  );
  NOT _43_ (
    .A(Fifo_errors[3]),
    .Y(_02_)
  );
  NOT _44_ (
    .A(state_estr[0]),
    .Y(_03_)
  );
  NOT _45_ (
    .A(state_estr[1]),
    .Y(_04_)
  );
  NOT _46_ (
    .A(state_estr[2]),
    .Y(_05_)
  );
  NOT _47_ (
    .A(umbralMF),
    .Y(_06_)
  );
  NOT _48_ (
    .A(umbralVC),
    .Y(_07_)
  );
  NOT _49_ (
    .A(umbralD),
    .Y(_08_)
  );
  NOT _50_ (
    .A(reset),
    .Y(_09_)
  );
  NOT _51_ (
    .A(Fifo_empties[0]),
    .Y(_10_)
  );
  NOR _52_ (
    .A(_03_),
    .B(state_estr[2]),
    .Y(_11_)
  );
  NAND _53_ (
    .A(state_estr[0]),
    .B(_05_),
    .Y(_12_)
  );
  NOR _54_ (
    .A(state_estr[1]),
    .B(_12_),
    .Y(_13_)
  );
  NAND _55_ (
    .A(_04_),
    .B(_11_),
    .Y(_14_)
  );
  NOR _56_ (
    .A(_08_),
    .B(_14_),
    .Y(umbralD_out)
  );
  NOR _57_ (
    .A(_07_),
    .B(_14_),
    .Y(umbralVC_out)
  );
  NOR _58_ (
    .A(_06_),
    .B(_14_),
    .Y(umbralMF_out)
  );
  NOR _59_ (
    .A(Fifo_errors[0]),
    .B(Fifo_errors[1]),
    .Y(_15_)
  );
  NAND _60_ (
    .A(_01_),
    .B(_02_),
    .Y(_16_)
  );
  NOR _61_ (
    .A(Fifo_errors[4]),
    .B(_16_),
    .Y(_17_)
  );
  NAND _62_ (
    .A(_15_),
    .B(_17_),
    .Y(_18_)
  );
  NOR _63_ (
    .A(state_estr[0]),
    .B(state_estr[1]),
    .Y(_19_)
  );
  NAND _64_ (
    .A(_03_),
    .B(_04_),
    .Y(_20_)
  );
  NAND _65_ (
    .A(state_estr[2]),
    .B(_19_),
    .Y(_21_)
  );
  NAND _66_ (
    .A(state_estr[2]),
    .B(_18_),
    .Y(_22_)
  );
  NOR _67_ (
    .A(_20_),
    .B(_22_),
    .Y(error_out)
  );
  NAND _68_ (
    .A(state_estr[1]),
    .B(_11_),
    .Y(_23_)
  );
  NOR _69_ (
    .A(_18_),
    .B(_23_),
    .Y(active_out)
  );
  NOR _70_ (
    .A(_04_),
    .B(_10_),
    .Y(_24_)
  );
  NAND _71_ (
    .A(Fifo_empties[1]),
    .B(Fifo_empties[2]),
    .Y(_25_)
  );
  NAND _72_ (
    .A(Fifo_empties[3]),
    .B(Fifo_empties[4]),
    .Y(_26_)
  );
  NOR _73_ (
    .A(_25_),
    .B(_26_),
    .Y(_27_)
  );
  NAND _74_ (
    .A(_24_),
    .B(_27_),
    .Y(_28_)
  );
  NOR _75_ (
    .A(state_estr[0]),
    .B(state_estr[2]),
    .Y(_29_)
  );
  NAND _76_ (
    .A(_03_),
    .B(_05_),
    .Y(_30_)
  );
  NOR _77_ (
    .A(_28_),
    .B(_30_),
    .Y(idle_out)
  );
  NOR _78_ (
    .A(umbralMF),
    .B(umbralVC),
    .Y(_31_)
  );
  NAND _79_ (
    .A(_08_),
    .B(_31_),
    .Y(_32_)
  );
  NAND _80_ (
    .A(_13_),
    .B(_32_),
    .Y(_33_)
  );
  NOT _81_ (
    .A(_33_),
    .Y(init_out)
  );
  NAND _82_ (
    .A(_05_),
    .B(_28_),
    .Y(_34_)
  );
  NOR _83_ (
    .A(state_estr[0]),
    .B(_34_),
    .Y(_35_)
  );
  NOR _84_ (
    .A(active_out),
    .B(_35_),
    .Y(_36_)
  );
  NOT _85_ (
    .A(_36_),
    .Y(next_state_estr[0])
  );
  NOR _86_ (
    .A(_09_),
    .B(_36_),
    .Y(_00_[0])
  );
  NAND _87_ (
    .A(state_estr[1]),
    .B(_29_),
    .Y(_37_)
  );
  NAND _88_ (
    .A(_33_),
    .B(_37_),
    .Y(_38_)
  );
  NOR _89_ (
    .A(active_out),
    .B(_38_),
    .Y(_39_)
  );
  NOT _90_ (
    .A(_39_),
    .Y(next_state_estr[1])
  );
  NOR _91_ (
    .A(_09_),
    .B(_39_),
    .Y(_00_[1])
  );
  NAND _92_ (
    .A(_21_),
    .B(_23_),
    .Y(_40_)
  );
  NAND _93_ (
    .A(_18_),
    .B(_40_),
    .Y(_41_)
  );
  NOT _94_ (
    .A(_41_),
    .Y(next_state_estr[2])
  );
  NOR _95_ (
    .A(_09_),
    .B(_41_),
    .Y(_00_[2])
  );
  (* src = "maquina.v:25" *)
  DFF _96_ (
    .C(clk),
    .D(_00_[0]),
    .Q(state_estr[0])
  );
  (* src = "maquina.v:25" *)
  DFF _97_ (
    .C(clk),
    .D(_00_[1]),
    .Q(state_estr[1])
  );
  (* src = "maquina.v:25" *)
  DFF _98_ (
    .C(clk),
    .D(_00_[2]),
    .Q(state_estr[2])
  );
  assign _00_[3] = 1'h0;
  assign next_state_estr[3] = 1'h0;
  assign state_estr[3] = 1'h0;
endmodule
