/* Generated by Yosys 0.7 (git sha1 61f6811, gcc 6.2.0-11ubuntu1 -O2 -fdebug-prefix-map=/build/yosys-OIL3SR/yosys-0.7=. -fstack-protector-strong -fPIC -Os) */

(* src = "flow_control_est.v:1" *)
module \$paramod\flow_control_est\BITNUMBER=6\LENGTH=4 (clk, reset, Fifo_rd, Fifo_wr, almost_full_est, almost_empty_est, Fifo_full_est, Fifo_empty_est, can_pop, pause);
  wire _0_;
  wire _1_;
  wire _2_;
  wire _3_;
  (* src = "flow_control_est.v:10" *)
  input Fifo_empty_est;
  (* src = "flow_control_est.v:9" *)
  input Fifo_full_est;
  (* src = "flow_control_est.v:5" *)
  input Fifo_rd;
  (* src = "flow_control_est.v:6" *)
  input Fifo_wr;
  (* src = "flow_control_est.v:8" *)
  input almost_empty_est;
  (* src = "flow_control_est.v:7" *)
  input almost_full_est;
  (* src = "flow_control_est.v:11" *)
  output can_pop;
  (* src = "flow_control_est.v:3" *)
  input clk;
  (* src = "flow_control_est.v:12" *)
  output pause;
  (* src = "flow_control_est.v:4" *)
  input reset;
  NOT _4_ (
    .A(almost_empty_est),
    .Y(_2_)
  );
  NOT _5_ (
    .A(Fifo_empty_est),
    .Y(_3_)
  );
  NAND _6_ (
    .A(_3_),
    .B(_2_),
    .Y(_0_)
  );
  NOR _7_ (
    .A(_0_),
    .B(reset),
    .Y(can_pop)
  );
  NOR _8_ (
    .A(Fifo_full_est),
    .B(almost_full_est),
    .Y(_1_)
  );
  NOR _9_ (
    .A(_1_),
    .B(reset),
    .Y(pause)
  );
endmodule

(* src = "memoria_est.v:1" *)
module \$paramod\memoria_est\BITNUMBER=6\LENGTH=4 (data_in, ptr_write, ptr_read, reset, clk, read, write, data_out);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  (* src = "memoria_est.v:7" *)
  input clk;
  (* src = "memoria_est.v:3" *)
  input [5:0] data_in;
  (* src = "memoria_est.v:10" *)
  output [5:0] data_out;
  wire [5:0] \mem[0] ;
  wire [5:0] \mem[1] ;
  wire [5:0] \mem[2] ;
  wire [5:0] \mem[3] ;
  (* src = "memoria_est.v:5" *)
  input [1:0] ptr_read;
  (* src = "memoria_est.v:4" *)
  input [1:0] ptr_write;
  (* src = "memoria_est.v:8" *)
  input read;
  (* src = "memoria_est.v:6" *)
  input reset;
  (* src = "memoria_est.v:9" *)
  input write;
  NOT _193_ (
    .A(reset),
    .Y(_159_)
  );
  NAND _194_ (
    .A(write),
    .B(_159_),
    .Y(_161_)
  );
  NOT _195_ (
    .A(ptr_write[1]),
    .Y(_163_)
  );
  NAND _196_ (
    .A(_163_),
    .B(ptr_write[0]),
    .Y(_164_)
  );
  NOR _197_ (
    .A(_164_),
    .B(_161_),
    .Y(_165_)
  );
  NOT _198_ (
    .A(\mem[1] [0]),
    .Y(_166_)
  );
  NOR _199_ (
    .A(reset),
    .B(_166_),
    .Y(_167_)
  );
  NOR _200_ (
    .A(_167_),
    .B(_165_),
    .Y(_168_)
  );
  NOT _201_ (
    .A(write),
    .Y(_169_)
  );
  NOR _202_ (
    .A(_169_),
    .B(reset),
    .Y(_170_)
  );
  NOT _203_ (
    .A(ptr_write[0]),
    .Y(_171_)
  );
  NOR _204_ (
    .A(ptr_write[1]),
    .B(_171_),
    .Y(_172_)
  );
  NAND _205_ (
    .A(_172_),
    .B(_170_),
    .Y(_173_)
  );
  NOR _206_ (
    .A(_173_),
    .B(data_in[0]),
    .Y(_174_)
  );
  NOR _207_ (
    .A(_174_),
    .B(_168_),
    .Y(_049_)
  );
  NOT _208_ (
    .A(\mem[1] [1]),
    .Y(_175_)
  );
  NOR _209_ (
    .A(reset),
    .B(_175_),
    .Y(_176_)
  );
  NOR _210_ (
    .A(_176_),
    .B(_165_),
    .Y(_177_)
  );
  NOR _211_ (
    .A(_173_),
    .B(data_in[1]),
    .Y(_178_)
  );
  NOR _212_ (
    .A(_178_),
    .B(_177_),
    .Y(_066_)
  );
  NOT _213_ (
    .A(\mem[1] [2]),
    .Y(_179_)
  );
  NOR _214_ (
    .A(reset),
    .B(_179_),
    .Y(_180_)
  );
  NOR _215_ (
    .A(_180_),
    .B(_165_),
    .Y(_181_)
  );
  NOR _216_ (
    .A(_173_),
    .B(data_in[2]),
    .Y(_182_)
  );
  NOR _217_ (
    .A(_182_),
    .B(_181_),
    .Y(_085_)
  );
  NOT _218_ (
    .A(\mem[1] [3]),
    .Y(_184_)
  );
  NOR _219_ (
    .A(reset),
    .B(_184_),
    .Y(_185_)
  );
  NOR _220_ (
    .A(_185_),
    .B(_165_),
    .Y(_187_)
  );
  NOR _221_ (
    .A(_173_),
    .B(data_in[3]),
    .Y(_188_)
  );
  NOR _222_ (
    .A(_188_),
    .B(_187_),
    .Y(_104_)
  );
  NOT _223_ (
    .A(\mem[1] [4]),
    .Y(_190_)
  );
  NOR _224_ (
    .A(reset),
    .B(_190_),
    .Y(_192_)
  );
  NOR _225_ (
    .A(_192_),
    .B(_165_),
    .Y(_000_)
  );
  NOR _226_ (
    .A(_173_),
    .B(data_in[4]),
    .Y(_002_)
  );
  NOR _227_ (
    .A(_002_),
    .B(_000_),
    .Y(_124_)
  );
  NOT _228_ (
    .A(\mem[1] [5]),
    .Y(_004_)
  );
  NOR _229_ (
    .A(reset),
    .B(_004_),
    .Y(_005_)
  );
  NOR _230_ (
    .A(_005_),
    .B(_165_),
    .Y(_006_)
  );
  NOR _231_ (
    .A(_173_),
    .B(data_in[5]),
    .Y(_007_)
  );
  NOR _232_ (
    .A(_007_),
    .B(_006_),
    .Y(_143_)
  );
  NAND _233_ (
    .A(_170_),
    .B(_171_),
    .Y(_008_)
  );
  NOR _234_ (
    .A(_008_),
    .B(_163_),
    .Y(_009_)
  );
  NOT _235_ (
    .A(\mem[2] [0]),
    .Y(_010_)
  );
  NOR _236_ (
    .A(reset),
    .B(_010_),
    .Y(_011_)
  );
  NOR _237_ (
    .A(_011_),
    .B(_009_),
    .Y(_012_)
  );
  NOR _238_ (
    .A(_161_),
    .B(ptr_write[0]),
    .Y(_013_)
  );
  NAND _239_ (
    .A(_013_),
    .B(ptr_write[1]),
    .Y(_014_)
  );
  NOR _240_ (
    .A(_014_),
    .B(data_in[0]),
    .Y(_015_)
  );
  NOR _241_ (
    .A(_015_),
    .B(_012_),
    .Y(_155_)
  );
  NOT _242_ (
    .A(\mem[2] [1]),
    .Y(_016_)
  );
  NOR _243_ (
    .A(reset),
    .B(_016_),
    .Y(_017_)
  );
  NOR _244_ (
    .A(_017_),
    .B(_009_),
    .Y(_018_)
  );
  NOR _245_ (
    .A(_014_),
    .B(data_in[1]),
    .Y(_019_)
  );
  NOR _246_ (
    .A(_019_),
    .B(_018_),
    .Y(_156_)
  );
  NOT _247_ (
    .A(\mem[2] [2]),
    .Y(_020_)
  );
  NOR _248_ (
    .A(reset),
    .B(_020_),
    .Y(_021_)
  );
  NOR _249_ (
    .A(_021_),
    .B(_009_),
    .Y(_022_)
  );
  NOR _250_ (
    .A(_014_),
    .B(data_in[2]),
    .Y(_023_)
  );
  NOR _251_ (
    .A(_023_),
    .B(_022_),
    .Y(_157_)
  );
  NOT _252_ (
    .A(\mem[2] [3]),
    .Y(_024_)
  );
  NOR _253_ (
    .A(reset),
    .B(_024_),
    .Y(_025_)
  );
  NOR _254_ (
    .A(_025_),
    .B(_009_),
    .Y(_026_)
  );
  NOR _255_ (
    .A(_014_),
    .B(data_in[3]),
    .Y(_027_)
  );
  NOR _256_ (
    .A(_027_),
    .B(_026_),
    .Y(_158_)
  );
  NOT _257_ (
    .A(\mem[2] [4]),
    .Y(_028_)
  );
  NOR _258_ (
    .A(reset),
    .B(_028_),
    .Y(_029_)
  );
  NOR _259_ (
    .A(_029_),
    .B(_009_),
    .Y(_031_)
  );
  NOR _260_ (
    .A(_014_),
    .B(data_in[4]),
    .Y(_032_)
  );
  NOR _261_ (
    .A(_032_),
    .B(_031_),
    .Y(_160_)
  );
  NOT _262_ (
    .A(\mem[2] [5]),
    .Y(_034_)
  );
  NOR _263_ (
    .A(reset),
    .B(_034_),
    .Y(_036_)
  );
  NOR _264_ (
    .A(_036_),
    .B(_009_),
    .Y(_037_)
  );
  NOR _265_ (
    .A(_014_),
    .B(data_in[5]),
    .Y(_039_)
  );
  NOR _266_ (
    .A(_039_),
    .B(_037_),
    .Y(_162_)
  );
  NOR _267_ (
    .A(_008_),
    .B(ptr_write[1]),
    .Y(_041_)
  );
  NOT _268_ (
    .A(\mem[0] [0]),
    .Y(_042_)
  );
  NOR _269_ (
    .A(reset),
    .B(_042_),
    .Y(_044_)
  );
  NOR _270_ (
    .A(_044_),
    .B(_041_),
    .Y(_045_)
  );
  NAND _271_ (
    .A(_013_),
    .B(_163_),
    .Y(_046_)
  );
  NOR _272_ (
    .A(_046_),
    .B(data_in[0]),
    .Y(_047_)
  );
  NOR _273_ (
    .A(_047_),
    .B(_045_),
    .Y(_183_)
  );
  NOT _274_ (
    .A(\mem[0] [1]),
    .Y(_048_)
  );
  NOR _275_ (
    .A(reset),
    .B(_048_),
    .Y(_050_)
  );
  NOR _276_ (
    .A(_050_),
    .B(_041_),
    .Y(_051_)
  );
  NOR _277_ (
    .A(_046_),
    .B(data_in[1]),
    .Y(_052_)
  );
  NOR _278_ (
    .A(_052_),
    .B(_051_),
    .Y(_186_)
  );
  NOT _279_ (
    .A(\mem[0] [2]),
    .Y(_053_)
  );
  NOR _280_ (
    .A(reset),
    .B(_053_),
    .Y(_054_)
  );
  NOR _281_ (
    .A(_054_),
    .B(_041_),
    .Y(_055_)
  );
  NOR _282_ (
    .A(_046_),
    .B(data_in[2]),
    .Y(_056_)
  );
  NOR _283_ (
    .A(_056_),
    .B(_055_),
    .Y(_189_)
  );
  NOT _284_ (
    .A(\mem[0] [3]),
    .Y(_057_)
  );
  NOR _285_ (
    .A(reset),
    .B(_057_),
    .Y(_058_)
  );
  NOR _286_ (
    .A(_058_),
    .B(_041_),
    .Y(_059_)
  );
  NOR _287_ (
    .A(_046_),
    .B(data_in[3]),
    .Y(_060_)
  );
  NOR _288_ (
    .A(_060_),
    .B(_059_),
    .Y(_191_)
  );
  NOT _289_ (
    .A(\mem[0] [4]),
    .Y(_061_)
  );
  NOR _290_ (
    .A(reset),
    .B(_061_),
    .Y(_062_)
  );
  NOR _291_ (
    .A(_062_),
    .B(_041_),
    .Y(_063_)
  );
  NOR _292_ (
    .A(_046_),
    .B(data_in[4]),
    .Y(_064_)
  );
  NOR _293_ (
    .A(_064_),
    .B(_063_),
    .Y(_001_)
  );
  NOT _294_ (
    .A(\mem[0] [5]),
    .Y(_065_)
  );
  NOR _295_ (
    .A(reset),
    .B(_065_),
    .Y(_067_)
  );
  NOR _296_ (
    .A(_067_),
    .B(_041_),
    .Y(_068_)
  );
  NOR _297_ (
    .A(_046_),
    .B(data_in[5]),
    .Y(_069_)
  );
  NOR _298_ (
    .A(_069_),
    .B(_068_),
    .Y(_003_)
  );
  NOT _299_ (
    .A(read),
    .Y(_070_)
  );
  NOT _300_ (
    .A(ptr_read[1]),
    .Y(_071_)
  );
  NOT _301_ (
    .A(\mem[3] [0]),
    .Y(_072_)
  );
  NOT _302_ (
    .A(ptr_read[0]),
    .Y(_073_)
  );
  NOR _303_ (
    .A(_073_),
    .B(_072_),
    .Y(_074_)
  );
  NOR _304_ (
    .A(ptr_read[0]),
    .B(_010_),
    .Y(_075_)
  );
  NOR _305_ (
    .A(_075_),
    .B(_074_),
    .Y(_076_)
  );
  NOR _306_ (
    .A(_076_),
    .B(_071_),
    .Y(_077_)
  );
  NOR _307_ (
    .A(_073_),
    .B(_166_),
    .Y(_078_)
  );
  NOR _308_ (
    .A(ptr_read[0]),
    .B(_042_),
    .Y(_079_)
  );
  NOR _309_ (
    .A(_079_),
    .B(_078_),
    .Y(_080_)
  );
  NOR _310_ (
    .A(_080_),
    .B(ptr_read[1]),
    .Y(_081_)
  );
  NOR _311_ (
    .A(_081_),
    .B(_077_),
    .Y(_082_)
  );
  NOR _312_ (
    .A(_082_),
    .B(_070_),
    .Y(data_out[0])
  );
  NOT _313_ (
    .A(\mem[3] [1]),
    .Y(_083_)
  );
  NOR _314_ (
    .A(_073_),
    .B(_083_),
    .Y(_084_)
  );
  NOR _315_ (
    .A(ptr_read[0]),
    .B(_016_),
    .Y(_086_)
  );
  NOR _316_ (
    .A(_086_),
    .B(_084_),
    .Y(_087_)
  );
  NOR _317_ (
    .A(_087_),
    .B(_071_),
    .Y(_088_)
  );
  NOR _318_ (
    .A(_073_),
    .B(_175_),
    .Y(_089_)
  );
  NOR _319_ (
    .A(ptr_read[0]),
    .B(_048_),
    .Y(_090_)
  );
  NOR _320_ (
    .A(_090_),
    .B(_089_),
    .Y(_091_)
  );
  NOR _321_ (
    .A(_091_),
    .B(ptr_read[1]),
    .Y(_092_)
  );
  NOR _322_ (
    .A(_092_),
    .B(_088_),
    .Y(_093_)
  );
  NOR _323_ (
    .A(_093_),
    .B(_070_),
    .Y(data_out[1])
  );
  NOT _324_ (
    .A(\mem[3] [2]),
    .Y(_094_)
  );
  NOR _325_ (
    .A(_073_),
    .B(_094_),
    .Y(_095_)
  );
  NOR _326_ (
    .A(ptr_read[0]),
    .B(_020_),
    .Y(_096_)
  );
  NOR _327_ (
    .A(_096_),
    .B(_095_),
    .Y(_097_)
  );
  NOR _328_ (
    .A(_097_),
    .B(_071_),
    .Y(_098_)
  );
  NOR _329_ (
    .A(_073_),
    .B(_179_),
    .Y(_099_)
  );
  NOR _330_ (
    .A(ptr_read[0]),
    .B(_053_),
    .Y(_100_)
  );
  NOR _331_ (
    .A(_100_),
    .B(_099_),
    .Y(_101_)
  );
  NOR _332_ (
    .A(_101_),
    .B(ptr_read[1]),
    .Y(_102_)
  );
  NOR _333_ (
    .A(_102_),
    .B(_098_),
    .Y(_103_)
  );
  NOR _334_ (
    .A(_103_),
    .B(_070_),
    .Y(data_out[2])
  );
  NOT _335_ (
    .A(\mem[3] [3]),
    .Y(_105_)
  );
  NOR _336_ (
    .A(_073_),
    .B(_105_),
    .Y(_106_)
  );
  NOR _337_ (
    .A(ptr_read[0]),
    .B(_024_),
    .Y(_107_)
  );
  NOR _338_ (
    .A(_107_),
    .B(_106_),
    .Y(_108_)
  );
  NOR _339_ (
    .A(_108_),
    .B(_071_),
    .Y(_109_)
  );
  NOR _340_ (
    .A(_073_),
    .B(_184_),
    .Y(_110_)
  );
  NOR _341_ (
    .A(ptr_read[0]),
    .B(_057_),
    .Y(_111_)
  );
  NOR _342_ (
    .A(_111_),
    .B(_110_),
    .Y(_112_)
  );
  NOR _343_ (
    .A(_112_),
    .B(ptr_read[1]),
    .Y(_113_)
  );
  NOR _344_ (
    .A(_113_),
    .B(_109_),
    .Y(_114_)
  );
  NOR _345_ (
    .A(_114_),
    .B(_070_),
    .Y(data_out[3])
  );
  NOT _346_ (
    .A(\mem[3] [4]),
    .Y(_115_)
  );
  NOR _347_ (
    .A(_073_),
    .B(_115_),
    .Y(_116_)
  );
  NOR _348_ (
    .A(ptr_read[0]),
    .B(_028_),
    .Y(_117_)
  );
  NOR _349_ (
    .A(_117_),
    .B(_116_),
    .Y(_118_)
  );
  NOR _350_ (
    .A(_118_),
    .B(_071_),
    .Y(_119_)
  );
  NOR _351_ (
    .A(_073_),
    .B(_190_),
    .Y(_120_)
  );
  NOR _352_ (
    .A(ptr_read[0]),
    .B(_061_),
    .Y(_121_)
  );
  NOR _353_ (
    .A(_121_),
    .B(_120_),
    .Y(_122_)
  );
  NOR _354_ (
    .A(_122_),
    .B(ptr_read[1]),
    .Y(_123_)
  );
  NOR _355_ (
    .A(_123_),
    .B(_119_),
    .Y(_125_)
  );
  NOR _356_ (
    .A(_125_),
    .B(_070_),
    .Y(data_out[4])
  );
  NOT _357_ (
    .A(\mem[3] [5]),
    .Y(_126_)
  );
  NOR _358_ (
    .A(_073_),
    .B(_126_),
    .Y(_127_)
  );
  NOR _359_ (
    .A(ptr_read[0]),
    .B(_034_),
    .Y(_128_)
  );
  NOR _360_ (
    .A(_128_),
    .B(_127_),
    .Y(_129_)
  );
  NOR _361_ (
    .A(_129_),
    .B(_071_),
    .Y(_130_)
  );
  NOR _362_ (
    .A(_073_),
    .B(_004_),
    .Y(_131_)
  );
  NOR _363_ (
    .A(ptr_read[0]),
    .B(_065_),
    .Y(_132_)
  );
  NOR _364_ (
    .A(_132_),
    .B(_131_),
    .Y(_133_)
  );
  NOR _365_ (
    .A(_133_),
    .B(ptr_read[1]),
    .Y(_134_)
  );
  NOR _366_ (
    .A(_134_),
    .B(_130_),
    .Y(_135_)
  );
  NOR _367_ (
    .A(_135_),
    .B(_070_),
    .Y(data_out[5])
  );
  NAND _368_ (
    .A(ptr_write[0]),
    .B(write),
    .Y(_136_)
  );
  NOR _369_ (
    .A(_136_),
    .B(_163_),
    .Y(_137_)
  );
  NOR _370_ (
    .A(_137_),
    .B(reset),
    .Y(_138_)
  );
  NAND _371_ (
    .A(_138_),
    .B(\mem[3] [0]),
    .Y(_139_)
  );
  NOR _372_ (
    .A(_171_),
    .B(_169_),
    .Y(_140_)
  );
  NAND _373_ (
    .A(_140_),
    .B(ptr_write[1]),
    .Y(_141_)
  );
  NOR _374_ (
    .A(_141_),
    .B(_161_),
    .Y(_142_)
  );
  NAND _375_ (
    .A(_142_),
    .B(data_in[0]),
    .Y(_144_)
  );
  NAND _376_ (
    .A(_144_),
    .B(_139_),
    .Y(_030_)
  );
  NAND _377_ (
    .A(_138_),
    .B(\mem[3] [1]),
    .Y(_145_)
  );
  NAND _378_ (
    .A(_142_),
    .B(data_in[1]),
    .Y(_146_)
  );
  NAND _379_ (
    .A(_146_),
    .B(_145_),
    .Y(_033_)
  );
  NAND _380_ (
    .A(_138_),
    .B(\mem[3] [2]),
    .Y(_147_)
  );
  NAND _381_ (
    .A(_142_),
    .B(data_in[2]),
    .Y(_148_)
  );
  NAND _382_ (
    .A(_148_),
    .B(_147_),
    .Y(_035_)
  );
  NAND _383_ (
    .A(_138_),
    .B(\mem[3] [3]),
    .Y(_149_)
  );
  NAND _384_ (
    .A(_142_),
    .B(data_in[3]),
    .Y(_150_)
  );
  NAND _385_ (
    .A(_150_),
    .B(_149_),
    .Y(_038_)
  );
  NAND _386_ (
    .A(_138_),
    .B(\mem[3] [4]),
    .Y(_151_)
  );
  NAND _387_ (
    .A(_142_),
    .B(data_in[4]),
    .Y(_152_)
  );
  NAND _388_ (
    .A(_152_),
    .B(_151_),
    .Y(_040_)
  );
  NAND _389_ (
    .A(_138_),
    .B(\mem[3] [5]),
    .Y(_153_)
  );
  NAND _390_ (
    .A(_142_),
    .B(data_in[5]),
    .Y(_154_)
  );
  NAND _391_ (
    .A(_154_),
    .B(_153_),
    .Y(_043_)
  );
  DFF _392_ (
    .C(clk),
    .D(_183_),
    .Q(\mem[0] [0])
  );
  DFF _393_ (
    .C(clk),
    .D(_186_),
    .Q(\mem[0] [1])
  );
  DFF _394_ (
    .C(clk),
    .D(_189_),
    .Q(\mem[0] [2])
  );
  DFF _395_ (
    .C(clk),
    .D(_191_),
    .Q(\mem[0] [3])
  );
  DFF _396_ (
    .C(clk),
    .D(_001_),
    .Q(\mem[0] [4])
  );
  DFF _397_ (
    .C(clk),
    .D(_003_),
    .Q(\mem[0] [5])
  );
  DFF _398_ (
    .C(clk),
    .D(_049_),
    .Q(\mem[1] [0])
  );
  DFF _399_ (
    .C(clk),
    .D(_066_),
    .Q(\mem[1] [1])
  );
  DFF _400_ (
    .C(clk),
    .D(_085_),
    .Q(\mem[1] [2])
  );
  DFF _401_ (
    .C(clk),
    .D(_104_),
    .Q(\mem[1] [3])
  );
  DFF _402_ (
    .C(clk),
    .D(_124_),
    .Q(\mem[1] [4])
  );
  DFF _403_ (
    .C(clk),
    .D(_143_),
    .Q(\mem[1] [5])
  );
  DFF _404_ (
    .C(clk),
    .D(_155_),
    .Q(\mem[2] [0])
  );
  DFF _405_ (
    .C(clk),
    .D(_156_),
    .Q(\mem[2] [1])
  );
  DFF _406_ (
    .C(clk),
    .D(_157_),
    .Q(\mem[2] [2])
  );
  DFF _407_ (
    .C(clk),
    .D(_158_),
    .Q(\mem[2] [3])
  );
  DFF _408_ (
    .C(clk),
    .D(_160_),
    .Q(\mem[2] [4])
  );
  DFF _409_ (
    .C(clk),
    .D(_162_),
    .Q(\mem[2] [5])
  );
  DFF _410_ (
    .C(clk),
    .D(_030_),
    .Q(\mem[3] [0])
  );
  DFF _411_ (
    .C(clk),
    .D(_033_),
    .Q(\mem[3] [1])
  );
  DFF _412_ (
    .C(clk),
    .D(_035_),
    .Q(\mem[3] [2])
  );
  DFF _413_ (
    .C(clk),
    .D(_038_),
    .Q(\mem[3] [3])
  );
  DFF _414_ (
    .C(clk),
    .D(_040_),
    .Q(\mem[3] [4])
  );
  DFF _415_ (
    .C(clk),
    .D(_043_),
    .Q(\mem[3] [5])
  );
endmodule

(* top =  1  *)
(* src = "fifo_est.v:3" *)
module fifo_est(Fifo_Data_in, clk, reset, Fifo_rd, Fifo_wr, Fifo_full_est, Fifo_empty_est, Fifo_Data_out_est, Fifo_rd_error_est, Fifo_wr_error_est, Fifo_error_est, almost_full_est, almost_empty_est, can_pop, pause, valid_read_est);
  (* src = "fifo_est.v:29" *)
  wire [5:0] _000_;
  (* src = "fifo_est.v:29" *)
  wire _001_;
  (* src = "fifo_est.v:29" *)
  wire _002_;
  (* src = "fifo_est.v:29" *)
  wire _003_;
  (* src = "fifo_est.v:29" *)
  wire _004_;
  (* src = "fifo_est.v:29" *)
  wire _005_;
  (* src = "fifo_est.v:29" *)
  wire _006_;
  (* src = "fifo_est.v:29" *)
  wire [2:0] _007_;
  (* src = "fifo_est.v:29" *)
  wire [5:0] _008_;
  (* src = "fifo_est.v:29" *)
  wire _009_;
  (* src = "fifo_est.v:29" *)
  wire _010_;
  (* src = "fifo_est.v:29" *)
  wire [1:0] _011_;
  (* src = "fifo_est.v:29" *)
  wire _012_;
  (* src = "fifo_est.v:29" *)
  wire _013_;
  (* src = "fifo_est.v:29" *)
  wire [1:0] _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  (* src = "fifo_est.v:5" *)
  input [5:0] Fifo_Data_in;
  (* src = "fifo_est.v:12" *)
  output [5:0] Fifo_Data_out_est;
  (* src = "fifo_est.v:11" *)
  output Fifo_empty_est;
  (* src = "fifo_est.v:15" *)
  output Fifo_error_est;
  (* src = "fifo_est.v:10" *)
  output Fifo_full_est;
  (* src = "fifo_est.v:8" *)
  input Fifo_rd;
  (* src = "fifo_est.v:13" *)
  output Fifo_rd_error_est;
  (* src = "fifo_est.v:9" *)
  input Fifo_wr;
  (* src = "fifo_est.v:14" *)
  output Fifo_wr_error_est;
  (* src = "fifo_est.v:17" *)
  output almost_empty_est;
  (* src = "fifo_est.v:16" *)
  output almost_full_est;
  (* src = "fifo_est.v:18" *)
  output can_pop;
  (* src = "fifo_est.v:6" *)
  input clk;
  (* src = "fifo_est.v:25" *)
  wire [2:0] contador;
  (* src = "fifo_est.v:19" *)
  output pause;
  (* src = "fifo_est.v:27" *)
  wire [5:0] q0;
  (* src = "fifo_est.v:26" *)
  wire [5:0] q1;
  (* src = "fifo_est.v:23" *)
  wire q_rd;
  (* src = "fifo_est.v:23" *)
  wire q_wt;
  (* src = "fifo_est.v:24" *)
  wire [1:0] rd_ptr;
  (* src = "fifo_est.v:7" *)
  input reset;
  (* src = "fifo_est.v:23" *)
  wire v1;
  (* src = "fifo_est.v:20" *)
  output valid_read_est;
  (* src = "fifo_est.v:24" *)
  wire [1:0] wr_ptr;
  NOT _119_ (
    .A(Fifo_wr),
    .Y(_085_)
  );
  NOR _120_ (
    .A(_085_),
    .B(Fifo_full_est),
    .Y(_086_)
  );
  NAND _121_ (
    .A(_086_),
    .B(contador[0]),
    .Y(_087_)
  );
  NOR _122_ (
    .A(_086_),
    .B(contador[0]),
    .Y(_088_)
  );
  NOR _123_ (
    .A(_088_),
    .B(reset),
    .Y(_089_)
  );
  NAND _124_ (
    .A(_089_),
    .B(_087_),
    .Y(_090_)
  );
  NOT _125_ (
    .A(Fifo_empty_est),
    .Y(_091_)
  );
  NAND _126_ (
    .A(Fifo_rd),
    .B(_091_),
    .Y(_092_)
  );
  NOT _127_ (
    .A(_092_),
    .Y(_093_)
  );
  NAND _128_ (
    .A(_093_),
    .B(_090_),
    .Y(_094_)
  );
  NOT _129_ (
    .A(contador[1]),
    .Y(_095_)
  );
  NOR _130_ (
    .A(_087_),
    .B(_095_),
    .Y(_096_)
  );
  NOT _131_ (
    .A(reset),
    .Y(_097_)
  );
  NAND _132_ (
    .A(_087_),
    .B(_095_),
    .Y(_098_)
  );
  NAND _133_ (
    .A(_098_),
    .B(_097_),
    .Y(_099_)
  );
  NOR _134_ (
    .A(_099_),
    .B(_096_),
    .Y(_100_)
  );
  NOR _135_ (
    .A(_100_),
    .B(_094_),
    .Y(_101_)
  );
  NOR _136_ (
    .A(_096_),
    .B(contador[2]),
    .Y(_102_)
  );
  NOT _137_ (
    .A(contador[2]),
    .Y(_103_)
  );
  NOT _138_ (
    .A(contador[0]),
    .Y(_104_)
  );
  NOT _139_ (
    .A(Fifo_full_est),
    .Y(_105_)
  );
  NAND _140_ (
    .A(Fifo_wr),
    .B(_105_),
    .Y(_106_)
  );
  NOR _141_ (
    .A(_106_),
    .B(_104_),
    .Y(_107_)
  );
  NAND _142_ (
    .A(_107_),
    .B(contador[1]),
    .Y(_108_)
  );
  NOR _143_ (
    .A(_108_),
    .B(_103_),
    .Y(_109_)
  );
  NOR _144_ (
    .A(_109_),
    .B(_102_),
    .Y(_110_)
  );
  NOR _145_ (
    .A(_110_),
    .B(_101_),
    .Y(_111_)
  );
  NAND _146_ (
    .A(_110_),
    .B(_101_),
    .Y(_112_)
  );
  NAND _147_ (
    .A(_112_),
    .B(_097_),
    .Y(_113_)
  );
  NOR _148_ (
    .A(_113_),
    .B(_111_),
    .Y(_007_[2])
  );
  NAND _149_ (
    .A(_106_),
    .B(_104_),
    .Y(_114_)
  );
  NAND _150_ (
    .A(_114_),
    .B(_097_),
    .Y(_115_)
  );
  NOR _151_ (
    .A(_115_),
    .B(_107_),
    .Y(_116_)
  );
  NOR _152_ (
    .A(_092_),
    .B(_116_),
    .Y(_117_)
  );
  NOR _153_ (
    .A(_093_),
    .B(_090_),
    .Y(_118_)
  );
  NOR _154_ (
    .A(_118_),
    .B(_117_),
    .Y(_015_)
  );
  NOR _155_ (
    .A(_015_),
    .B(reset),
    .Y(_007_[0])
  );
  NOR _156_ (
    .A(_107_),
    .B(contador[1]),
    .Y(_016_)
  );
  NOR _157_ (
    .A(_016_),
    .B(reset),
    .Y(_017_)
  );
  NAND _158_ (
    .A(_017_),
    .B(_108_),
    .Y(_018_)
  );
  NAND _159_ (
    .A(_018_),
    .B(_117_),
    .Y(_019_)
  );
  NAND _160_ (
    .A(_100_),
    .B(_094_),
    .Y(_020_)
  );
  NAND _161_ (
    .A(_020_),
    .B(_019_),
    .Y(_021_)
  );
  NAND _162_ (
    .A(_021_),
    .B(_097_),
    .Y(_022_)
  );
  NAND _163_ (
    .A(_022_),
    .B(_007_[0]),
    .Y(_023_)
  );
  NOR _164_ (
    .A(_023_),
    .B(_007_[2]),
    .Y(_005_)
  );
  NAND _165_ (
    .A(_021_),
    .B(_007_[0]),
    .Y(_024_)
  );
  NOR _166_ (
    .A(_024_),
    .B(_007_[2]),
    .Y(_006_)
  );
  NAND _167_ (
    .A(_092_),
    .B(_116_),
    .Y(_025_)
  );
  NAND _168_ (
    .A(_025_),
    .B(_094_),
    .Y(_026_)
  );
  NAND _169_ (
    .A(_026_),
    .B(_097_),
    .Y(_027_)
  );
  NAND _170_ (
    .A(_022_),
    .B(_027_),
    .Y(_028_)
  );
  NOR _171_ (
    .A(_028_),
    .B(_007_[2]),
    .Y(_001_)
  );
  NOT _172_ (
    .A(q1[0]),
    .Y(_029_)
  );
  NOR _173_ (
    .A(_029_),
    .B(reset),
    .Y(_000_[0])
  );
  NOT _174_ (
    .A(q1[1]),
    .Y(_030_)
  );
  NOR _175_ (
    .A(_030_),
    .B(reset),
    .Y(_000_[1])
  );
  NOT _176_ (
    .A(q1[2]),
    .Y(_031_)
  );
  NOR _177_ (
    .A(_031_),
    .B(reset),
    .Y(_000_[2])
  );
  NOT _178_ (
    .A(q1[3]),
    .Y(_032_)
  );
  NOR _179_ (
    .A(_032_),
    .B(reset),
    .Y(_000_[3])
  );
  NOT _180_ (
    .A(q1[4]),
    .Y(_033_)
  );
  NOR _181_ (
    .A(_033_),
    .B(reset),
    .Y(_000_[4])
  );
  NOT _182_ (
    .A(q1[5]),
    .Y(_034_)
  );
  NOR _183_ (
    .A(_034_),
    .B(reset),
    .Y(_000_[5])
  );
  NOR _184_ (
    .A(reset),
    .B(_085_),
    .Y(_010_)
  );
  NOT _185_ (
    .A(_010_),
    .Y(_035_)
  );
  NOR _186_ (
    .A(_035_),
    .B(_105_),
    .Y(_004_)
  );
  NOR _187_ (
    .A(_111_),
    .B(reset),
    .Y(_036_)
  );
  NAND _188_ (
    .A(_036_),
    .B(_112_),
    .Y(_037_)
  );
  NOR _189_ (
    .A(_028_),
    .B(_037_),
    .Y(_002_)
  );
  NOT _190_ (
    .A(v1),
    .Y(_038_)
  );
  NOR _191_ (
    .A(_038_),
    .B(reset),
    .Y(_013_)
  );
  NAND _192_ (
    .A(_097_),
    .B(Fifo_rd),
    .Y(_039_)
  );
  NAND _193_ (
    .A(q_rd),
    .B(reset),
    .Y(_040_)
  );
  NAND _194_ (
    .A(_040_),
    .B(_039_),
    .Y(_009_)
  );
  NOR _195_ (
    .A(_092_),
    .B(reset),
    .Y(_012_)
  );
  NOR _196_ (
    .A(_039_),
    .B(_091_),
    .Y(_003_)
  );
  NOT _197_ (
    .A(rd_ptr[0]),
    .Y(_041_)
  );
  NOR _198_ (
    .A(_092_),
    .B(_041_),
    .Y(_042_)
  );
  NAND _199_ (
    .A(_092_),
    .B(_041_),
    .Y(_043_)
  );
  NAND _200_ (
    .A(_043_),
    .B(_097_),
    .Y(_044_)
  );
  NOR _201_ (
    .A(_044_),
    .B(_042_),
    .Y(_011_[0])
  );
  NOT _202_ (
    .A(rd_ptr[1]),
    .Y(_045_)
  );
  NOR _203_ (
    .A(_042_),
    .B(_045_),
    .Y(_046_)
  );
  NOT _204_ (
    .A(_042_),
    .Y(_047_)
  );
  NOR _205_ (
    .A(_047_),
    .B(rd_ptr[1]),
    .Y(_048_)
  );
  NOR _206_ (
    .A(_048_),
    .B(_046_),
    .Y(_049_)
  );
  NOR _207_ (
    .A(_049_),
    .B(reset),
    .Y(_011_[1])
  );
  NOR _208_ (
    .A(_086_),
    .B(q0[0]),
    .Y(_050_)
  );
  NOT _209_ (
    .A(Fifo_Data_in[0]),
    .Y(_051_)
  );
  NAND _210_ (
    .A(_086_),
    .B(_051_),
    .Y(_052_)
  );
  NAND _211_ (
    .A(_052_),
    .B(_097_),
    .Y(_053_)
  );
  NOR _212_ (
    .A(_053_),
    .B(_050_),
    .Y(_008_[0])
  );
  NOR _213_ (
    .A(_086_),
    .B(q0[1]),
    .Y(_054_)
  );
  NOT _214_ (
    .A(Fifo_Data_in[1]),
    .Y(_055_)
  );
  NAND _215_ (
    .A(_086_),
    .B(_055_),
    .Y(_056_)
  );
  NAND _216_ (
    .A(_056_),
    .B(_097_),
    .Y(_057_)
  );
  NOR _217_ (
    .A(_057_),
    .B(_054_),
    .Y(_008_[1])
  );
  NOR _218_ (
    .A(_086_),
    .B(q0[2]),
    .Y(_058_)
  );
  NOT _219_ (
    .A(Fifo_Data_in[2]),
    .Y(_059_)
  );
  NAND _220_ (
    .A(_086_),
    .B(_059_),
    .Y(_060_)
  );
  NAND _221_ (
    .A(_060_),
    .B(_097_),
    .Y(_061_)
  );
  NOR _222_ (
    .A(_061_),
    .B(_058_),
    .Y(_008_[2])
  );
  NOR _223_ (
    .A(_086_),
    .B(q0[3]),
    .Y(_062_)
  );
  NOT _224_ (
    .A(Fifo_Data_in[3]),
    .Y(_063_)
  );
  NAND _225_ (
    .A(_086_),
    .B(_063_),
    .Y(_064_)
  );
  NAND _226_ (
    .A(_064_),
    .B(_097_),
    .Y(_065_)
  );
  NOR _227_ (
    .A(_065_),
    .B(_062_),
    .Y(_008_[3])
  );
  NOR _228_ (
    .A(_086_),
    .B(q0[4]),
    .Y(_066_)
  );
  NOT _229_ (
    .A(Fifo_Data_in[4]),
    .Y(_067_)
  );
  NAND _230_ (
    .A(_086_),
    .B(_067_),
    .Y(_068_)
  );
  NAND _231_ (
    .A(_068_),
    .B(_097_),
    .Y(_069_)
  );
  NOR _232_ (
    .A(_069_),
    .B(_066_),
    .Y(_008_[4])
  );
  NOR _233_ (
    .A(_086_),
    .B(q0[5]),
    .Y(_070_)
  );
  NOT _234_ (
    .A(Fifo_Data_in[5]),
    .Y(_071_)
  );
  NAND _235_ (
    .A(_086_),
    .B(_071_),
    .Y(_072_)
  );
  NAND _236_ (
    .A(_072_),
    .B(_097_),
    .Y(_073_)
  );
  NOR _237_ (
    .A(_073_),
    .B(_070_),
    .Y(_008_[5])
  );
  NOT _238_ (
    .A(wr_ptr[0]),
    .Y(_074_)
  );
  NOR _239_ (
    .A(_106_),
    .B(_074_),
    .Y(_075_)
  );
  NAND _240_ (
    .A(_106_),
    .B(_074_),
    .Y(_076_)
  );
  NAND _241_ (
    .A(_076_),
    .B(_097_),
    .Y(_077_)
  );
  NOR _242_ (
    .A(_077_),
    .B(_075_),
    .Y(_014_[0])
  );
  NOT _243_ (
    .A(wr_ptr[1]),
    .Y(_078_)
  );
  NOR _244_ (
    .A(_075_),
    .B(_078_),
    .Y(_079_)
  );
  NOT _245_ (
    .A(_075_),
    .Y(_080_)
  );
  NOR _246_ (
    .A(_080_),
    .B(wr_ptr[1]),
    .Y(_081_)
  );
  NOR _247_ (
    .A(_081_),
    .B(_079_),
    .Y(_082_)
  );
  NOR _248_ (
    .A(_082_),
    .B(reset),
    .Y(_014_[1])
  );
  NOT _249_ (
    .A(_022_),
    .Y(_007_[1])
  );
  NOT _250_ (
    .A(Fifo_rd_error_est),
    .Y(_083_)
  );
  NOT _251_ (
    .A(Fifo_wr_error_est),
    .Y(_084_)
  );
  NAND _252_ (
    .A(_084_),
    .B(_083_),
    .Y(Fifo_error_est)
  );
  DFF _253_ (
    .C(clk),
    .D(_005_),
    .Q(almost_empty_est)
  );
  DFF _254_ (
    .C(clk),
    .D(_006_),
    .Q(almost_full_est)
  );
  DFF _255_ (
    .C(clk),
    .D(_002_),
    .Q(Fifo_full_est)
  );
  DFF _256_ (
    .C(clk),
    .D(_001_),
    .Q(Fifo_empty_est)
  );
  DFF _257_ (
    .C(clk),
    .D(_000_[0]),
    .Q(Fifo_Data_out_est[0])
  );
  DFF _258_ (
    .C(clk),
    .D(_000_[1]),
    .Q(Fifo_Data_out_est[1])
  );
  DFF _259_ (
    .C(clk),
    .D(_000_[2]),
    .Q(Fifo_Data_out_est[2])
  );
  DFF _260_ (
    .C(clk),
    .D(_000_[3]),
    .Q(Fifo_Data_out_est[3])
  );
  DFF _261_ (
    .C(clk),
    .D(_000_[4]),
    .Q(Fifo_Data_out_est[4])
  );
  DFF _262_ (
    .C(clk),
    .D(_000_[5]),
    .Q(Fifo_Data_out_est[5])
  );
  DFF _263_ (
    .C(clk),
    .D(_003_),
    .Q(Fifo_rd_error_est)
  );
  DFF _264_ (
    .C(clk),
    .D(_004_),
    .Q(Fifo_wr_error_est)
  );
  DFF _265_ (
    .C(clk),
    .D(_013_),
    .Q(valid_read_est)
  );
  DFF _266_ (
    .C(clk),
    .D(_010_),
    .Q(q_wt)
  );
  DFF _267_ (
    .C(clk),
    .D(_009_),
    .Q(q_rd)
  );
  DFF _268_ (
    .C(clk),
    .D(_012_),
    .Q(v1)
  );
  DFF _269_ (
    .C(clk),
    .D(_011_[0]),
    .Q(rd_ptr[0])
  );
  DFF _270_ (
    .C(clk),
    .D(_011_[1]),
    .Q(rd_ptr[1])
  );
  DFF _271_ (
    .C(clk),
    .D(_014_[0]),
    .Q(wr_ptr[0])
  );
  DFF _272_ (
    .C(clk),
    .D(_014_[1]),
    .Q(wr_ptr[1])
  );
  DFF _273_ (
    .C(clk),
    .D(_007_[0]),
    .Q(contador[0])
  );
  DFF _274_ (
    .C(clk),
    .D(_007_[1]),
    .Q(contador[1])
  );
  DFF _275_ (
    .C(clk),
    .D(_007_[2]),
    .Q(contador[2])
  );
  DFF _276_ (
    .C(clk),
    .D(_008_[0]),
    .Q(q0[0])
  );
  DFF _277_ (
    .C(clk),
    .D(_008_[1]),
    .Q(q0[1])
  );
  DFF _278_ (
    .C(clk),
    .D(_008_[2]),
    .Q(q0[2])
  );
  DFF _279_ (
    .C(clk),
    .D(_008_[3]),
    .Q(q0[3])
  );
  DFF _280_ (
    .C(clk),
    .D(_008_[4]),
    .Q(q0[4])
  );
  DFF _281_ (
    .C(clk),
    .D(_008_[5]),
    .Q(q0[5])
  );
  (* src = "fifo_est.v:106" *)
  \$paramod\flow_control_est\BITNUMBER=6\LENGTH=4  flow_c_ (
    .Fifo_empty_est(Fifo_empty_est),
    .Fifo_full_est(Fifo_full_est),
    .Fifo_rd(Fifo_rd),
    .Fifo_wr(Fifo_wr),
    .almost_empty_est(almost_empty_est),
    .almost_full_est(almost_full_est),
    .can_pop(can_pop),
    .clk(clk),
    .pause(pause),
    .reset(reset)
  );
  (* src = "fifo_est.v:98" *)
  \$paramod\memoria_est\BITNUMBER=6\LENGTH=4  memoria_est (
    .clk(clk),
    .data_in(q0),
    .data_out(q1),
    .ptr_read(rd_ptr),
    .ptr_write(wr_ptr),
    .read(q_rd),
    .reset(reset),
    .write(q_wt)
  );
endmodule
