/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* dynports =  1  *)
(* top =  1  *)
(* src = "mux_dest.v:1" *)
module mux_dest_synth(clk, reset, data_in0, data_in1, valid_VC0, valid_VC1, valid_out_dest, data_out_dest);
  (* src = "mux_dest.v:35" *)
  wire [4:0] _00_;
  (* src = "mux_dest.v:35" *)
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _30_;
  wire _31_;
  wire _32_;
  wire _33_;
  (* src = "mux_dest.v:11" *)
  (* unused_bits = "0 1 2 3 4" *)
  wire [5:0] ValueHold_Out;
  (* src = "mux_dest.v:2" *)
  input clk;
  (* src = "mux_dest.v:4" *)
  input [4:0] data_in0;
  (* src = "mux_dest.v:5" *)
  input [4:0] data_in1;
  (* src = "mux_dest.v:9" *)
  output [4:0] data_out_dest;
  (* src = "mux_dest.v:3" *)
  input reset;
  (* src = "mux_dest.v:6" *)
  input valid_VC0;
  (* src = "mux_dest.v:7" *)
  input valid_VC1;
  (* src = "mux_dest.v:8" *)
  output valid_out_dest;
  NOT _34_ (
    .A(reset),
    .Y(_02_)
  );
  NOT _35_ (
    .A(valid_VC1),
    .Y(_03_)
  );
  NOT _36_ (
    .A(valid_VC0),
    .Y(_04_)
  );
  NOT _37_ (
    .A(data_in1[0]),
    .Y(_05_)
  );
  NOT _38_ (
    .A(data_in1[1]),
    .Y(_06_)
  );
  NOT _39_ (
    .A(data_in1[2]),
    .Y(_07_)
  );
  NOT _40_ (
    .A(data_in1[3]),
    .Y(_08_)
  );
  NOT _41_ (
    .A(data_in1[4]),
    .Y(_09_)
  );
  NAND _42_ (
    .A(valid_VC1),
    .B(_04_),
    .Y(_10_)
  );
  NOR _43_ (
    .A(_06_),
    .B(_10_),
    .Y(_11_)
  );
  NAND _44_ (
    .A(valid_VC0),
    .B(data_in0[1]),
    .Y(_12_)
  );
  NOT _45_ (
    .A(_12_),
    .Y(_13_)
  );
  NOR _46_ (
    .A(_11_),
    .B(_13_),
    .Y(_14_)
  );
  NOR _47_ (
    .A(_02_),
    .B(_14_),
    .Y(_00_[1])
  );
  NOR _48_ (
    .A(_07_),
    .B(_10_),
    .Y(_15_)
  );
  NAND _49_ (
    .A(valid_VC0),
    .B(data_in0[2]),
    .Y(_16_)
  );
  NOT _50_ (
    .A(_16_),
    .Y(_17_)
  );
  NOR _51_ (
    .A(_15_),
    .B(_17_),
    .Y(_18_)
  );
  NOR _52_ (
    .A(_02_),
    .B(_18_),
    .Y(_00_[2])
  );
  NOR _53_ (
    .A(_08_),
    .B(_10_),
    .Y(_19_)
  );
  NAND _54_ (
    .A(valid_VC0),
    .B(data_in0[3]),
    .Y(_20_)
  );
  NOT _55_ (
    .A(_20_),
    .Y(_21_)
  );
  NOR _56_ (
    .A(_19_),
    .B(_21_),
    .Y(_22_)
  );
  NOR _57_ (
    .A(_02_),
    .B(_22_),
    .Y(_00_[3])
  );
  NOR _58_ (
    .A(_09_),
    .B(_10_),
    .Y(_23_)
  );
  NAND _59_ (
    .A(valid_VC0),
    .B(data_in0[4]),
    .Y(_24_)
  );
  NOT _60_ (
    .A(_24_),
    .Y(_25_)
  );
  NOR _61_ (
    .A(_23_),
    .B(_25_),
    .Y(_26_)
  );
  NOR _62_ (
    .A(_02_),
    .B(_26_),
    .Y(_00_[4])
  );
  NAND _63_ (
    .A(_03_),
    .B(_04_),
    .Y(_27_)
  );
  NAND _64_ (
    .A(reset),
    .B(_27_),
    .Y(_28_)
  );
  NAND _65_ (
    .A(_02_),
    .B(valid_out_dest),
    .Y(_29_)
  );
  NAND _66_ (
    .A(_28_),
    .B(_29_),
    .Y(_01_)
  );
  NOR _67_ (
    .A(_05_),
    .B(_10_),
    .Y(_30_)
  );
  NAND _68_ (
    .A(valid_VC0),
    .B(data_in0[0]),
    .Y(_31_)
  );
  NOT _69_ (
    .A(_31_),
    .Y(_32_)
  );
  NOR _70_ (
    .A(_30_),
    .B(_32_),
    .Y(_33_)
  );
  NOR _71_ (
    .A(_02_),
    .B(_33_),
    .Y(_00_[0])
  );
  (* src = "mux_dest.v:35" *)
  DFF _72_ (
    .C(clk),
    .D(_01_),
    .Q(valid_out_dest)
  );
  (* src = "mux_dest.v:35" *)
  DFF _73_ (
    .C(clk),
    .D(_00_[0]),
    .Q(data_out_dest[0])
  );
  (* src = "mux_dest.v:35" *)
  DFF _74_ (
    .C(clk),
    .D(_00_[1]),
    .Q(data_out_dest[1])
  );
  (* src = "mux_dest.v:35" *)
  DFF _75_ (
    .C(clk),
    .D(_00_[2]),
    .Q(data_out_dest[2])
  );
  (* src = "mux_dest.v:35" *)
  DFF _76_ (
    .C(clk),
    .D(_00_[3]),
    .Q(data_out_dest[3])
  );
  (* src = "mux_dest.v:35" *)
  DFF _77_ (
    .C(clk),
    .D(_00_[4]),
    .Q(data_out_dest[4])
  );
  assign ValueHold_Out[5] = 1'h0;
endmodule
