/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* dynports =  1  *)
(* top =  1  *)
(* src = "mux_dest.v:1" *)
module mux_dest_synth(clk, reset, data_in0, data_in1, valid_VC0, valid_VC1, valid_out_dest0, valid_out_dest1, data_out_dest);
  (* src = "mux_dest.v:40" *)
  wire [4:0] _00_;
  (* src = "mux_dest.v:40" *)
  wire _01_;
  (* src = "mux_dest.v:40" *)
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  (* src = "mux_dest.v:12" *)
  (* unused_bits = "0 1 2 3 4" *)
  wire [5:0] ValueHold_Out;
  (* src = "mux_dest.v:2" *)
  input clk;
  (* src = "mux_dest.v:4" *)
  input [4:0] data_in0;
  (* src = "mux_dest.v:5" *)
  input [4:0] data_in1;
  (* src = "mux_dest.v:10" *)
  output [4:0] data_out_dest;
  (* src = "mux_dest.v:13" *)
  wire interValidValue0;
  (* src = "mux_dest.v:3" *)
  input reset;
  (* src = "mux_dest.v:6" *)
  input valid_VC0;
  (* src = "mux_dest.v:7" *)
  input valid_VC1;
  (* src = "mux_dest.v:8" *)
  output valid_out_dest0;
  (* src = "mux_dest.v:9" *)
  output valid_out_dest1;
  NOT _23_ (
    .A(valid_VC0),
    .Y(_03_)
  );
  NOT _24_ (
    .A(reset),
    .Y(_04_)
  );
  NOT _25_ (
    .A(valid_VC1),
    .Y(_05_)
  );
  NOR _26_ (
    .A(_03_),
    .B(_04_),
    .Y(_06_)
  );
  NAND _27_ (
    .A(valid_VC0),
    .B(reset),
    .Y(_07_)
  );
  NAND _28_ (
    .A(data_in0[0]),
    .B(_06_),
    .Y(_08_)
  );
  NAND _29_ (
    .A(_03_),
    .B(reset),
    .Y(_09_)
  );
  NOR _30_ (
    .A(_05_),
    .B(_09_),
    .Y(_10_)
  );
  NOT _31_ (
    .A(_10_),
    .Y(_11_)
  );
  NAND _32_ (
    .A(data_in1[0]),
    .B(_10_),
    .Y(_12_)
  );
  NAND _33_ (
    .A(_08_),
    .B(_12_),
    .Y(_00_[0])
  );
  NAND _34_ (
    .A(data_in0[1]),
    .B(_06_),
    .Y(_13_)
  );
  NAND _35_ (
    .A(data_in1[1]),
    .B(_10_),
    .Y(_14_)
  );
  NAND _36_ (
    .A(_13_),
    .B(_14_),
    .Y(_00_[1])
  );
  NAND _37_ (
    .A(data_in0[2]),
    .B(_06_),
    .Y(_15_)
  );
  NAND _38_ (
    .A(data_in1[2]),
    .B(_10_),
    .Y(_16_)
  );
  NAND _39_ (
    .A(_15_),
    .B(_16_),
    .Y(_00_[2])
  );
  NAND _40_ (
    .A(data_in0[3]),
    .B(_06_),
    .Y(_17_)
  );
  NAND _41_ (
    .A(data_in1[3]),
    .B(_10_),
    .Y(_18_)
  );
  NAND _42_ (
    .A(_17_),
    .B(_18_),
    .Y(_00_[3])
  );
  NAND _43_ (
    .A(data_in0[4]),
    .B(_06_),
    .Y(_19_)
  );
  NAND _44_ (
    .A(data_in1[4]),
    .B(_10_),
    .Y(_20_)
  );
  NAND _45_ (
    .A(_19_),
    .B(_20_),
    .Y(_00_[4])
  );
  NAND _46_ (
    .A(_04_),
    .B(valid_out_dest1),
    .Y(_21_)
  );
  NAND _47_ (
    .A(_11_),
    .B(_21_),
    .Y(_02_)
  );
  NAND _48_ (
    .A(_04_),
    .B(valid_out_dest0),
    .Y(_22_)
  );
  NAND _49_ (
    .A(_07_),
    .B(_22_),
    .Y(_01_)
  );
  (* src = "mux_dest.v:40" *)
  DFF _50_ (
    .C(clk),
    .D(_01_),
    .Q(valid_out_dest0)
  );
  (* src = "mux_dest.v:40" *)
  DFF _51_ (
    .C(clk),
    .D(_02_),
    .Q(valid_out_dest1)
  );
  (* src = "mux_dest.v:40" *)
  DFF _52_ (
    .C(clk),
    .D(_00_[0]),
    .Q(data_out_dest[0])
  );
  (* src = "mux_dest.v:40" *)
  DFF _53_ (
    .C(clk),
    .D(_00_[1]),
    .Q(data_out_dest[1])
  );
  (* src = "mux_dest.v:40" *)
  DFF _54_ (
    .C(clk),
    .D(_00_[2]),
    .Q(data_out_dest[2])
  );
  (* src = "mux_dest.v:40" *)
  DFF _55_ (
    .C(clk),
    .D(_00_[3]),
    .Q(data_out_dest[3])
  );
  (* src = "mux_dest.v:40" *)
  DFF _56_ (
    .C(clk),
    .D(_00_[4]),
    .Q(data_out_dest[4])
  );
  assign ValueHold_Out[5] = 1'h0;
  assign interValidValue0 = valid_VC0;
endmodule
