/* Generated by Yosys 0.7 (git sha1 61f6811, gcc 6.2.0-11ubuntu1 -O2 -fdebug-prefix-map=/build/yosys-OIL3SR/yosys-0.7=. -fstack-protector-strong -fPIC -Os) */

(* top =  1  *)
(* src = "maquina.v:1" *)
module maquina_synth(clk, reset, umbralMF, umbralVC, umbralD, FifoFull, FifoEmpty, FifoWrite, FifoRead, init_out, idle_out, active_out, error_out, state_estr, next_state_estr);
  (* src = "maquina.v:23" *)
  wire [3:0] _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  (* src = "maquina.v:7" *)
  input FifoEmpty;
  (* src = "maquina.v:6" *)
  input FifoFull;
  (* src = "maquina.v:9" *)
  input FifoRead;
  (* src = "maquina.v:8" *)
  input FifoWrite;
  (* src = "maquina.v:12" *)
  output active_out;
  (* src = "maquina.v:1" *)
  input clk;
  (* src = "maquina.v:13" *)
  output error_out;
  (* src = "maquina.v:11" *)
  output idle_out;
  (* src = "maquina.v:10" *)
  output init_out;
  (* src = "maquina.v:15" *)
  output [3:0] next_state_estr;
  (* src = "maquina.v:2" *)
  input reset;
  (* src = "maquina.v:14" *)
  output [3:0] state_estr;
  (* src = "maquina.v:5" *)
  input umbralD;
  (* src = "maquina.v:3" *)
  input umbralMF;
  (* src = "maquina.v:4" *)
  input umbralVC;
  NOR _051_ (
    .A(FifoFull),
    .B(FifoEmpty),
    .Y(_001_)
  );
  NOT _052_ (
    .A(state_estr[0]),
    .Y(_002_)
  );
  NOR _053_ (
    .A(state_estr[2]),
    .B(state_estr[3]),
    .Y(_003_)
  );
  NAND _054_ (
    .A(_003_),
    .B(state_estr[1]),
    .Y(_004_)
  );
  NOR _055_ (
    .A(_004_),
    .B(_002_),
    .Y(_005_)
  );
  NAND _056_ (
    .A(_005_),
    .B(_001_),
    .Y(_006_)
  );
  NOT _057_ (
    .A(_006_),
    .Y(active_out)
  );
  NOT _058_ (
    .A(state_estr[1]),
    .Y(_007_)
  );
  NOT _059_ (
    .A(state_estr[3]),
    .Y(_008_)
  );
  NOT _060_ (
    .A(state_estr[2]),
    .Y(_009_)
  );
  NAND _061_ (
    .A(_009_),
    .B(_008_),
    .Y(_010_)
  );
  NOR _062_ (
    .A(_010_),
    .B(_007_),
    .Y(_011_)
  );
  NAND _063_ (
    .A(_011_),
    .B(_002_),
    .Y(_012_)
  );
  NOT _064_ (
    .A(FifoFull),
    .Y(_013_)
  );
  NAND _065_ (
    .A(_013_),
    .B(FifoEmpty),
    .Y(_014_)
  );
  NOR _066_ (
    .A(_014_),
    .B(_012_),
    .Y(idle_out)
  );
  NAND _067_ (
    .A(_007_),
    .B(state_estr[0]),
    .Y(_015_)
  );
  NOT _068_ (
    .A(umbralVC),
    .Y(_016_)
  );
  NOR _069_ (
    .A(umbralD),
    .B(umbralMF),
    .Y(_017_)
  );
  NAND _070_ (
    .A(_017_),
    .B(_016_),
    .Y(_018_)
  );
  NAND _071_ (
    .A(_018_),
    .B(_003_),
    .Y(_019_)
  );
  NOR _072_ (
    .A(_019_),
    .B(_015_),
    .Y(init_out)
  );
  NAND _073_ (
    .A(FifoFull),
    .B(FifoEmpty),
    .Y(_020_)
  );
  NAND _074_ (
    .A(_020_),
    .B(_005_),
    .Y(_021_)
  );
  NOR _075_ (
    .A(state_estr[0]),
    .B(state_estr[3]),
    .Y(_022_)
  );
  NAND _076_ (
    .A(_022_),
    .B(_009_),
    .Y(_023_)
  );
  NOR _077_ (
    .A(_001_),
    .B(_007_),
    .Y(_024_)
  );
  NOR _078_ (
    .A(_024_),
    .B(_023_),
    .Y(_025_)
  );
  NOT _079_ (
    .A(_025_),
    .Y(_026_)
  );
  NAND _080_ (
    .A(_026_),
    .B(_021_),
    .Y(next_state_estr[0])
  );
  NOT _081_ (
    .A(reset),
    .Y(_027_)
  );
  NAND _082_ (
    .A(_011_),
    .B(state_estr[0]),
    .Y(_028_)
  );
  NOT _083_ (
    .A(_020_),
    .Y(_029_)
  );
  NOR _084_ (
    .A(_029_),
    .B(_028_),
    .Y(_030_)
  );
  NOR _085_ (
    .A(_025_),
    .B(_030_),
    .Y(_031_)
  );
  NOR _086_ (
    .A(_031_),
    .B(_027_),
    .Y(_000_[0])
  );
  NOR _087_ (
    .A(_029_),
    .B(_012_),
    .Y(_032_)
  );
  NOR _088_ (
    .A(_032_),
    .B(init_out),
    .Y(_033_)
  );
  NAND _089_ (
    .A(_033_),
    .B(_006_),
    .Y(next_state_estr[1])
  );
  NOR _090_ (
    .A(_015_),
    .B(_010_),
    .Y(_034_)
  );
  NAND _091_ (
    .A(_034_),
    .B(_018_),
    .Y(_035_)
  );
  NAND _092_ (
    .A(_035_),
    .B(_006_),
    .Y(_036_)
  );
  NOR _093_ (
    .A(_036_),
    .B(_032_),
    .Y(_037_)
  );
  NOR _094_ (
    .A(_037_),
    .B(_027_),
    .Y(_000_[1])
  );
  NOR _095_ (
    .A(_020_),
    .B(_004_),
    .Y(_038_)
  );
  NOT _096_ (
    .A(_038_),
    .Y(_039_)
  );
  NAND _097_ (
    .A(state_estr[2]),
    .B(_007_),
    .Y(_040_)
  );
  NOR _098_ (
    .A(_040_),
    .B(_013_),
    .Y(_041_)
  );
  NOT _099_ (
    .A(_022_),
    .Y(_042_)
  );
  NOR _100_ (
    .A(FifoWrite),
    .B(FifoRead),
    .Y(_043_)
  );
  NOR _101_ (
    .A(_043_),
    .B(_042_),
    .Y(_044_)
  );
  NAND _102_ (
    .A(_044_),
    .B(_041_),
    .Y(_045_)
  );
  NAND _103_ (
    .A(_045_),
    .B(_039_),
    .Y(next_state_estr[2])
  );
  NAND _104_ (
    .A(_022_),
    .B(state_estr[2]),
    .Y(_046_)
  );
  NOR _105_ (
    .A(_046_),
    .B(_043_),
    .Y(_047_)
  );
  NAND _106_ (
    .A(_047_),
    .B(_007_),
    .Y(_048_)
  );
  NOR _107_ (
    .A(_048_),
    .B(_013_),
    .Y(_049_)
  );
  NOR _108_ (
    .A(_049_),
    .B(_038_),
    .Y(_050_)
  );
  NOR _109_ (
    .A(_050_),
    .B(_027_),
    .Y(_000_[2])
  );
  DFF _110_ (
    .C(clk),
    .D(_000_[0]),
    .Q(state_estr[0])
  );
  DFF _111_ (
    .C(clk),
    .D(_000_[1]),
    .Q(state_estr[1])
  );
  DFF _112_ (
    .C(clk),
    .D(_000_[2]),
    .Q(state_estr[2])
  );
  DFF _113_ (
    .C(clk),
    .D(1'b0),
    .Q(state_estr[3])
  );
  assign error_out = 1'b0;
  assign next_state_estr[3] = 1'b0;
endmodule
